### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Kflash** [Kflash/boogy#3]
This is the remaining tasks. But I have no more time atm.

- [x] make sure the code is 100% after the specs
- [x] Simplify and cleanup the code
- [x] Improve performance even more

**Comment by Kflash** [comment]
@TrySound If you have time and lust, could you trim the source code down from 900 lines to around 4 - 500?

**Comment by Kflash** [comment]
Closing. Fixed.
