### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Kflash** [Kflash/boogy#9]
- [x] fix so all NodeJS 6.x stuff works for NodeJS 4.x in loose mode
- [x]  support for  ES2016 &&  ES2017 and beyond (*strict mode for now*)
- [x] improve performance further
